kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  annotations:
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: permit-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        deployment: frontend
    spec:
      serviceAccountName: issues
      imagePullSecrets:
      - name: acr-creds
      volumes:
        - name: fe-storage
          persistentVolumeClaim:
            claimName: fe-storage
      containers:
        - name: frontend
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: fe-storage
              mountPath: /usr/log
          env:
            - name: TESTPERMIT_MICROSERVICES_LOG_FOLDER_PATH
              value: /usr/log
            - name: TESTPERMIT_MICROSERVICES_API_URL
              valueFrom:
                configMapKeyRef:
                  name: testpermit-microservices-config
                  key: testpermitmicroservicesapiurl
          image: goaaroregistry.azurecr.io/024087d6-4aa7-4a52-90ec-0db8ffe1249e/dlh-dev/permit-frontend:eff6b8dc02c4cbf8c4d55c1707d4e383cc589263

