kind: Deployment
apiVersion: apps/v1
metadata:
  name: testpermit-api
  annotations:
  labels:
    app: testpermit-api
    app.kubernetes.io/component: testpermit-api
    app.kubernetes.io/instance: testpermit-api
    app.kubernetes.io/name: testpermit-api
    app.kubernetes.io/part-of: permit-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testpermit-api
  template:
    metadata:
      annotations: 
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'issues'
        vault.hashicorp.com/agent-inject-secret-config: 'secret/data/issues/config'
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/issues/config" -}}
          databaseuser="{{ .Data.data.dbuser }}"
          databasepassword="{{ .Data.data.dbpwd }}"
          {{- end -}}
      labels:
        app: testpermit-api
        deployment: testpermit-api
    spec:
      serviceAccountName: issues
      imagePullSecrets:
      - name: acr-creds
      containers:
        - name: testpermit-api
          ports:
            - containerPort: 8080
              protocol: TCP

          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: databasehost
                  name: testpermit-microservices-config
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: databasename
                  name: testpermit-microservices-config 
            - name: VAULT_PSQL_PROPERTIES
              value: /vault/secrets/config

          image: goaaroregistry.azurecr.io/024087d6-4aa7-4a52-90ec-0db8ffe1249e/dlh-dev/permit-api:eff6b8dc02c4cbf8c4d55c1707d4e383cc589263
