apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: AspNetCoreWebApi6
    app.kubernetes.io/component: AspNetCoreWebApi6
    app.kubernetes.io/instance: AspNetCoreWebApi6
    app.kubernetes.io/name: AspNetCoreWebApi6
    app.kubernetes.io/part-of: AspNetCoreWebApi6
  name: AspNetCoreWebApi6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AspNetCoreWebApi6
  template:
    metadata:
      labels:
        app: AspNetCoreWebApi6
        deployment: AspNetCoreWebApi6
    spec:
      containers:
      - image: goaaroregistry.azurecr.io/024087d6-4aa7-4a52-90ec-0db8ffe1249e/dlh-dev/AspNetCoreWebApi6:17afdcdf8d16f0c1b54b34a38479374ffbed3141
        name: AspNetCoreWebApi6
      imagePullSecrets:
      - name: acr-creds
