apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: permit-microservices
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        deployment: frontend
    spec:
      containers:
      - env:
        - name: TESTPERMIT_MICROSERVICES_LOG_FOLDER_PATH
          value: /usr/log
        - name: TESTPERMIT_MICROSERVICES_API_URL
          valueFrom:
            configMapKeyRef:
              key: testpermitmicroservicesapiurl
              name: testpermit-microservices-config
        image: goaaroregistry.azurecr.io/024087d6-4aa7-4a52-90ec-0db8ffe1249e/dlh-dev/permit-frontend@sha256:6d48d30f9dd4dcbf6a317316e6f5607128b317984d1357a669749f2bb0472d62
        name: frontend
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/log
          name: fe-storage
      imagePullSecrets:
      - name: acr-creds
      serviceAccountName: issues
      volumes:
      - name: fe-storage
        persistentVolumeClaim:
          claimName: fe-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testpermit-api
    app.kubernetes.io/component: testpermit-api
    app.kubernetes.io/instance: testpermit-api
    app.kubernetes.io/name: testpermit-api
    app.kubernetes.io/part-of: permit-microservices
  name: testpermit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testpermit-api
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-config: secret/data/issues/config
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/issues/config" -}}
          databaseuser="{{ .Data.data.dbuser }}"
          databasepassword="{{ .Data.data.dbpwd }}"
          {{- end -}}
        vault.hashicorp.com/role: issues
      labels:
        app: testpermit-api
        deployment: testpermit-api
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              key: databasehost
              name: testpermit-microservices-config
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: databasename
              name: testpermit-microservices-config
        - name: VAULT_PSQL_PROPERTIES
          value: /vault/secrets/config
        image: goaaroregistry.azurecr.io/024087d6-4aa7-4a52-90ec-0db8ffe1249e/dlh-dev/permit-api@sha256:dba0350041553ed53e45785510d5571dc24bf997a33e4be112025c5957638a38
        name: testpermit-api
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: acr-creds
      serviceAccountName: issues
